apiVersion: v1
kind: Service
metadata:
  name: hashing-service
spec:
  type: NodePort
  selector:
    app: hashing-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
