apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'hashing-service'
        static_configs:
          - targets: ['hashing-service:8000']
      - job_name: 'length-service'
        static_configs:
          - targets: ['length-service:8001']
