apiVersion: v1
kind: Service
metadata:
  name: length-service
spec:
  type: NodePort
  selector:
    app: length-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
